# -*- coding: utf-8 -*-
"""cd_projeto_aplicado_IV_entrega_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10cutq57jRX79Bd-sSg2lOlBv_OTQGvol

<img src="https://raw.githubusercontent.com/scalabrinig/cdProjetoAplicadoIV/d093146488f56dfcf0ef286bcee8efe0e71b9c76/figuras/mackenzie_logo.jpg" width="25%" align="right"/>

# **PROJETO APLICADO IV - Ciência de Dados EaD - 2024/02**


# **Entrega 3**

---

# **Impactos da Mudança Climática na Biodiversidade Terrestre no Brasil**
"""

#@title **Identificação do Grupo e Opção do Projeto**

#@markdown Integrantes do Grupo, nome completo em ordem alfabética (*informe: \<nome\>, \<matrícula\>*)
Aluno1 = 'Antônio Alcivan da Silva, 10407102' #@param {type:"string"}
Aluno2 = 'Ítalo Pedro dos Santos Pereira, 10407172' #@param {type:"string"}
Aluno3 = 'Joyce Rhaellem Alves Costa, 10408023' #@param {type:"string"}
Aluno4 = 'Priscila Gabrielly Mendes, 10407319' #@param {type:"string"}
Aluno5 = 'Rafael Kazuo Kondo, 10178765' #@param {type:"string"}

"""# **Introdução**

Este projeto se insere no contexto das mudanças climáticas globais, com foco nas interações entre o clima e os ecossistemas terrestres, particularmente na biodiversidade, uma das áreas mais impactadas por esse fenômeno. A abordagem multidisciplinar deste estudo abrange ciências ambientais, climatologia e sustentabilidade, áreas fundamentais para a compreensão das interações entre atividades humanas e o meio ambiente. Alinhado ao Objetivo de Desenvolvimento Sustentável (ODS) 15 - Vida Terrestre, que visa proteger, restaurar e promover o uso sustentável dos ecossistemas, o projeto buscará identificar e mitigar os efeitos das mudanças climáticas sobre a biodiversidade no Brasil, com ênfase nas florestas tropicais, como a Amazônia e a Mata Atlântica.

As mudanças climáticas representam um dos maiores desafios do século XXI, sendo caracterizadas por alterações nos padrões climáticos globais, impulsionadas pela emissão de gases de efeito estufa (GEE) e pela modificação do uso da terra, como o desmatamento. Esses fenômenos têm provocado eventos climáticos extremos, como secas, enchentes e elevação do nível do mar, além de impactar diretamente a biodiversidade e os serviços ecossistêmicos essenciais à vida humana, como a purificação da água e a fertilidade do solo. Diante desses impactos, torna-se imperativo o desenvolvimento de políticas públicas e práticas sustentáveis que visem mitigar as consequências das mudanças climáticas, promovendo a adaptação das populações e ecossistemas vulneráveis.

A motivação para este projeto surge da necessidade urgente de compreender e mitigar os efeitos da mudança climática sobre a biodiversidade, especialmente no Brasil, que abriga ecossistemas de importância global. A degradação ambiental afeta diretamente os serviços ecossistêmicos e as populações que dependem desses recursos, como comunidades indígenas e rurais. Portanto, este estudo visa contribuir para a preservação da biodiversidade, propondo soluções que possam ser aplicadas em nível local e global, com potencial de influenciar políticas públicas e práticas empresariais sustentáveis.

O objetivo geral é desenvolver um produto analítico baseado em séries temporais, capaz de analisar e prever os impactos das mudanças climáticas sobre a biodiversidade terrestre no Brasil. Para isso, pretende-se coletar e integrar dados públicos sobre clima e biodiversidade, analisar os impactos das mudanças climáticas nos ecossistemas, desenvolver modelos previsionais e propor soluções para mitigar os efeitos adversos dessas alterações.

Os objetivos específicos do projeto incluem a coleta e integração de dados, reunindo informações de fontes públicas sobre clima e biodiversidade, como séries temporais de temperatura, precipitação e registros de biodiversidade, extraídos de bases como INMET, MapBiomas, Our World in Data e CEMADEN. Além disso, será realizada uma análise de impactos, com o objetivo de identificar padrões e tendências nas mudanças climáticas e seus efeitos sobre a biodiversidade, utilizando técnicas de análise de séries temporais. O projeto também visa o desenvolvimento de modelos previsionais, que permitirão prever os impactos futuros das mudanças climáticas sobre os ecossistemas terrestres no Brasil. Outro objetivo é a proposição de soluções, com a apresentação de estratégias para mitigar esses impactos, promovendo a adaptação tanto dos ecossistemas quanto das comunidades humanas. Por fim, haverá a disseminação de resultados, com a divulgação dos achados do projeto para a comunidade científica, tomadores de decisão e o público em geral, promovendo a conscientização e incentivando ações sustentáveis.

<br/>As análises utilizarão uma integração de diversas bases de dados, como:

- __IMF - Annual Surface Temperature Change:__ Dados anuais sobre mudanças de temperatura da superfície.<br/>
https://climatedata.imf.org/datasets/4063314923d74187be9596f10d034914_0/explore

- __Our World in Data - Climate Change:__ Indicadores sobre mudanças climáticas.<br/>
https://ourworldindata.org/climate-change

- __INMET - Dados Históricos:__ Informações climáticas do Brasil, como temperatura e precipitação.<br/>
https://portal.inmet.gov.br/dadoshistoricos

- __MapBiomas - Coleções MapBiomas:__ Dados sobre uso e cobertura da terra no Brasil.<br/>
https://brasil.mapbiomas.org/colecoes-mapbiomas/

- __CEMADEN - Monitoramento de Seca no Brasil:__ Dados sobre secas e seus impactos no Brasil.<br/>
https://www.gov.br/cemaden/pt-br/assuntos/monitoramento/monitoramento-de-seca-para-o-brasil/monitoramento-de-secas-e-impactos-no-brasil-2013-setembro-2023-1

<br/>Com a utilização dessas bases de dados, o projeto tem como objetivo fornecer uma visão detalhada das relações entre mudanças climáticas e biodiversidade no Brasil, contribuindo para a formulação de políticas públicas e a implementação de práticas mais sustentáveis.

# **Referencial Teórico**

__1. Impacto das Mudanças Climáticas na Biodiversidade Brasileira - Correio Braziliense__<br/>
- Metodologia: Os autores realizaram uma revisão de literatura sobre os efeitos das mudanças climáticas em diferentes ecossistemas brasileiros. Foi feita uma análise qualitativa das fontes disponíveis, coletando dados de diversas pesquisas relacionadas ao tema.<br/>
- Modelo Utilizado: A pesquisa não utilizou um modelo quantitativo específico, mas suas conclusões se basearam em análises de tendências observadas em estudos anteriores.<br/>
- Contexto do Trabalho: Este trabalho insere-se na análise dos impactos das mudanças climáticas na biodiversidade, focando especificamente na degradação de habitats naturais e na extinção de espécies em diferentes biomas do Brasil.
- Link: https://www.correiobraziliense.com.br/opiniao/2024/03/6819366-impacto-das-mudancas-climaticas-na-biodiversidade-brasileira.html

__2. Impactos das Mudanças Climáticas no Brasil - Climainfo__<br/>
- Metodologia: Os pesquisadores compilaram dados de diversas fontes climáticas e ecológicas para mapear as alterações nas condições ambientais ao longo do tempo. Foram feitas correlações entre os dados climáticos e as mudanças na biodiversidade.<br/>
- Modelo Utilizado: O estudo não se concentrou em um modelo de previsão específico, mas analisou dados históricos para identificar padrões e tendências, levando a uma previsão de riscos potenciais para a biodiversidade.<br/>
- Contexto do Trabalho: Este trabalho se insere na avaliação do impacto das mudanças climáticas sobre a biodiversidade, com foco nas variações de temperatura e precipitação em diferentes regiões do Brasil.
- Link: https://climainfo.org.br/2022/02/28/impactos-das-mudancas-climaticas-brasil/

__3. Mudanças Climáticas e Biodiversidade - WWF Brasil__<br/>
- Metodologia:O estudo utilizou uma abordagem de revisão sistemática, analisando dados de relatórios científicos e estatísticas sobre a biodiversidade e as mudanças climáticas. A análise incluiu uma limpeza de dados e a comparação de várias fontes.<br/>
- Modelo Utilizado: Não foi especificado um modelo preditivo, mas a WWF fez uso de modelos ecológicos para prever cenários de perda de biodiversidade com base nas mudanças climáticas.<br/>
- Contexto do Trabalho: O trabalho se insere na discussão sobre as interações entre mudanças climáticas e biodiversidade, enfatizando a importância da conservação em áreas críticas do Brasil.
- Link: https://www.wwf.org.br/natureza_brasileira/reducao_de_impactos2/clima/mudancas_climaticas2/

__4. Mudanças Climáticas e Agricultura - Embrapa__<br/>
- Metodologia: O estudo baseou-se na análise de dados de produtividade agrícola e nas condições climáticas nos últimos anos, utilizando técnicas de modelagem estatística para entender as correlações entre as variáveis.<br/>
- Modelo Utilizado: A Embrapa utilizou modelos de previsão climática para avaliar os impactos das mudanças nas práticas agrícolas, identificando um impacto direto na produção de alimentos.<br/>
- Contexto do Trabalho: Este trabalho insere-se na análise dos impactos das mudanças climáticas na agricultura brasileira, ressaltando as consequências para a biodiversidade e os ecossistemas que suportam a produção de alimentos.
- Link: https://ainfo.cnptia.embrapa.br/digital/bitstream/item/188635/1/Mudancas-climaticas.pdf

__5. O Que Sabemos Sobre a Biodiversidade e as Mudanças Climáticas no Brasil - WWF Brasil__<br/>
- Metodologia: Os autores realizaram uma síntese de informações provenientes de várias pesquisas e relatórios, utilizando uma abordagem analítica para identificar tendências e padrões em relação à biodiversidade e às mudanças climáticas.<br/>
- Modelo Utilizado: O estudo não mencionou um modelo preditivo, mas suas conclusões foram fundamentadas em dados compilados de diversas fontes científicas.<br/>
- Contexto do Trabalho: Este trabalho se insere na análise da relação entre mudanças climáticas e biodiversidade no Brasil, discutindo a importância de ações conservacionistas para proteger espécies ameaçadas.
- Link: https://www.wwf.org.br/?65562/O-que-sabemos-sobre-a-biodiversidade-e-as-mudanas-climticas-no-Brasil

<br/>Contribuição para a Definição da Metodologia do Nosso Trabalho
Os artigos selecionados contribuíram significativamente para a definição da metodologia do nosso trabalho ao fornecerem uma base sólida de informações sobre os impactos das mudanças climáticas na biodiversidade brasileira. A revisão das abordagens metodológicas, como a análise de dados climáticos e a utilização de modelos preditivos, nos ajudou a estruturar nossa própria pesquisa. Além disso, a identificação de lacunas na literatura existente nos motivou a explorar novos ângulos e a integrar análises qualitativas e quantitativas em nosso estudo, proporcionando uma compreensão mais abrangente dos efeitos das mudanças climáticas na biodiversidade.

# **Pré-Processamento dos Dados**

Os códigos utilizados no projeto foram listados e especificados abaixo. E conforme determinado no entregável da terceira etapa, todos os códigos foram testados e as bases foram anexadas dentro do Google Colab, com o objetivo final de serem 100% executáveis e reproduzíveis. <br/>
<br/>
### 1. Bibliotecas Utilizadas
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""### 2. Definição dos Caminhos dos Arquivos (Dentro do Google Colab)."""

file_paths = {
    'global_temperature_anomalies': '/content/global-temperature-anomalies-by-month (1).csv',
    'wildfires_area_burnt': '/content/cumulative-area-burnt-by-wildfires-by-week.csv',
    'natural_disasters': '/content/natural-disasters.csv',
    'temperature_anomaly': '/content/temperature-anomaly.csv',
    'annual_mean_temperature': '/content/Indicator_3_1_Climate_Indicators_Annual_Mean_Global_Surface_Temperature_-6404917154628205853.csv',
    'new_global_temp': '/content/Indicator_3_1_Climate_Indicators_Annual_Mean_Global_Surface_Temperature_7838445144233466279 (1).csv'
}

"""### 3. Carregar e Preparar cada Conjunto de Dados"""

dataframes = {name: pd.read_csv(path) for name, path in file_paths.items()}

"""### 4. Preparação das Anomalias Globais de Temperatura"""

global_temperature_anomalies_df = dataframes['global_temperature_anomalies'].groupby('Year').agg(
    avg_temp_anomaly=('Temperature anomaly', 'mean')
).reset_index()

"""### 5. Área Queimada por Incêncios (Foco Global)"""

wildfires_area_burnt_df = dataframes['wildfires_area_burnt'].melt(
    id_vars=['Year'],
    value_vars=[col for col in dataframes['wildfires_area_burnt'].columns if 'Cumulative area burnt' in col],
    var_name='Yearly_Burnt_Area',
    value_name='burnt_area'
).groupby('Year').agg({'burnt_area': 'max'}).reset_index()

"""### 6. Desastres Naturais (Foco Global)"""

natural_disasters_df = dataframes['natural_disasters'].groupby('Year').agg(
    total_disasters=('Number of total people affected by drought', 'sum'),
    drought_impact=('Number of people affected from drought', 'sum')
).reset_index()

"""### 7. Anomalias de Temperatura (Relaticos a 1961 a 1990)"""

temperature_anomaly_df = dataframes['temperature_anomaly'].groupby('Year').agg(
    avg_temp_anomaly=('Global average temperature anomaly relative to 1961-1990', 'mean')
).reset_index()

"""### 8. Temperatura Média Anual Global"""

annual_mean_temp_df = dataframes['annual_mean_temperature'].melt(
    id_vars=['Country'],
    value_vars=[str(year) for year in range(1961, 2024)],
    var_name='Year',
    value_name='mean_temp'
).groupby('Year').agg({'mean_temp': 'mean'}).reset_index()

"""### 9. Novo Conjunto de Temperatura Média Global"""

new_global_temp_df = dataframes['new_global_temp'].melt(
    id_vars=['Country'],
    value_vars=[str(year) for year in range(1961, 2024)],
    var_name='Year',
    value_name='mean_global_temp'
).groupby('Year').agg({'mean_global_temp': 'mean'}).reset_index()

"""### 10. Garantir que todas as colunas 'Year' estejam no tipo inteiro para evitar erros de fusão"""

annual_mean_temp_df['Year'] = annual_mean_temp_df['Year'].astype(int)
new_global_temp_df['Year'] = new_global_temp_df['Year'].astype(int)
global_temperature_anomalies_df['Year'] = global_temperature_anomalies_df['Year'].astype(int)
wildfires_area_burnt_df['Year'] = wildfires_area_burnt_df['Year'].astype(int)
natural_disasters_df['Year'] = natural_disasters_df['Year'].astype(int)
temperature_anomaly_df['Year'] = temperature_anomaly_df['Year'].astype(int)

"""### 11. Consolidar os dados globais em um único DataFrame novamente"""

merged_data_global = pd.merge(annual_mean_temp_df, new_global_temp_df, on="Year", how="left")
merged_data_global = pd.merge(merged_data_global, global_temperature_anomalies_df, on="Year", how="left")
merged_data_global = pd.merge(merged_data_global, wildfires_area_burnt_df, on="Year", how="left")
merged_data_global = pd.merge(merged_data_global, natural_disasters_df, on="Year", how="left")
merged_data_global = pd.merge(merged_data_global, temperature_anomaly_df, on="Year", how="left")

"""### 12. Renomear colunas duplicadas para evitar confusão"""

merged_data_global = merged_data_global.rename(columns={'avg_temp_anomaly_x': 'avg_temp_anomaly_1961_1990', 'avg_temp_anomaly_y': 'avg_temp_anomaly_1951_1980'})

"""### 13. Verificar e preencher valores ausentes (se houver) para permitir análise contínua"""

merged_data_global = merged_data_global.fillna(0)

"""### 14. Análise de correlação detalhada entre variáveis globais"""

correlation_matrix_global = merged_data_global[['mean_temp', 'mean_global_temp', 'avg_temp_anomaly_1961_1990', 'avg_temp_anomaly_1951_1980', 'burnt_area', 'total_disasters', 'drought_impact']].corr()

"""### 15. Visualização de correlação entre variáveis globais"""

plt.figure(figsize=(12, 10))
sns.heatmap(correlation_matrix_global, annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Correlação entre Variáveis Climáticas e Impactos Naturais a Nível Global")
plt.show()

"""# **Análise exploratória**

A imagem de correlação mostra as inter-relações entre diversas variáveis climáticas e de impacto natural, a nível global. Abaixo, explicaremos cada correlação observada, com foco em como os aumentos de temperatura se relacionam com os desastres naturais, queimadas e as anomalias climáticas.

## Detalhes das Correlações

### __1.Temperatura Média Global vs. Anomalias de Temperatura__

#### Correlação entre mean_temp e avg_temp_anomaly_1961_1990:
> Esta correlação é positiva e próxima de 1, indicando que, à medida que a temperatura média global aumenta, as anomalias em relação à média de 1961-1990 também aumentam. Esse comportamento é esperado, pois anomalias representam desvios das médias históricas, e o aumento das temperaturas globais intensifica esses desvios.

#### Correlação entre mean_global_temp e avg_temp_anomaly_1951_1980:
> Esta correlação também é muito forte e positiva. Ela revela uma relação direta entre o aumento das temperaturas globais e as anomalias de temperatura baseadas no período de 1951-1980, reforçando que o aquecimento global está amplificando os desvios das médias climáticas passadas.

### __2.Temperatura vs. Área Queimada por Incêndios (burnt_area)__

#### Correlação entre mean_temp e burnt_area:
> Esta correlação positiva indica que, à medida que a temperatura média global sobe, a área queimada por incêndios tende a aumentar. Isso faz sentido, pois temperaturas mais altas estão frequentemente associadas a climas mais secos, o que cria condições ideais para incêndios. Assim, regiões com aumentos de temperatura mais acentuados experimentam maiores áreas de vegetação queimadas.

#### Correlação entre avg_temp_anomaly_1961_1990 e burnt_area:
> Uma correlação positiva aqui sugere que as anomalias de temperatura também estão associadas ao aumento da área queimada. Como as anomalias refletem variações em relação a um padrão climático passado, essas anomalias crescentes indicam uma mudança climática significativa que contribui para condições propícias a incêndios.

### __3.Temperatura vs. Desastres Naturais__

#### Correlação entre mean_temp e total_disasters:
> Essa relação positiva sugere que o aumento da temperatura média global está associado ao aumento no número de desastres naturais. Isso pode incluir eventos como enchentes, secas e tempestades, que se tornam mais intensos e frequentes com o aquecimento global.

#### Correlação entre mean_temp e drought_impact:
> Uma correlação positiva indica que o impacto das secas aumenta com o aumento das temperaturas globais. O aquecimento global contribui para a redução da umidade do solo e aumento da evaporação, intensificando as secas em várias regiões do mundo.

### __4.Relação entre Incêndios e Desastres Naturais__

#### Correlação entre burnt_area e total_disasters:
> Essa correlação indica que áreas com maiores incêndios também apresentam mais desastres naturais em geral, sugerindo uma conexão indireta entre as condições propícias a incêndios e outras consequências climáticas extremas. A relação pode estar ligada ao fato de que incêndios florestais afetam a vegetação e o solo, reduzindo a capacidade de absorção de água e contribuindo para deslizamentos e enchentes.

### __5.Interpretação Geral__

> Essas correlações sugerem que o aumento da temperatura global está diretamente ligado a uma série de consequências ambientais adversas, como um número crescente de desastres naturais e incêndios. A análise reforça a necessidade de monitoramento e mitigação, pois os eventos climáticos extremos parecem intensificar-se com o aumento das anomalias e da temperatura média global, colocando ecossistemas e biodiversidade em risco.

# **Pipeline da Solução**

A Pipeline foi montada e elaborada dentro do Google Colab, com as bases em formato .csv anexadas, permitindo a importação, e o tratamento feito através da linguagem de programação Python.

__1. Coleta de Dados:__<br/>
Reunir dados públicos das fontes mencionadas (IMF, Our World in Data, INMET, MapBiomas, CEMADEN) usando APIs e downloads em formatos CSV, JSON ou geoJSON.

__2. Armazenamento:__<br/>
Armazenar os dados em um repositório central (ex: Amazon S3, Google Cloud Storage) e organizar por período e região.

__3. Processamento:__<br/>
Limpeza e transformação dos dados (Python/Pandas).
Integração dos dados por país, ano e bioma. Exemplo: Spark para processar grandes volumes.

__4. Análise de Séries Temporais:__<br/>
Aplicar técnicas como ARIMA ou Prophet para análise e previsão de tendências climáticas e impactos na biodiversidade.

__5. Desenvolvimento de Modelos Previsionais:__<br/>
Treinar modelos de aprendizado de máquina para prever o impacto das mudanças climáticas em ecossistemas sensíveis.

__6. Visualização e Comunicação:__<br/>
Criar dashboards interativos (Power BI, Looker Studio) para exibir dados e previsões.
Geração de relatórios com insights para decisões políticas.

__7.Desafios e Limitações:__<br/>

Integrar dados de diferentes formatos e granularidades.
Lidar com dados faltantes e inconsistências.
Este pipeline permite analisar e prever os impactos das mudanças climáticas sobre a biodiversidade, promovendo políticas de preservação ambiental.

# **Modelo Base**

Conforme alinhado para a terceira etapa do Projeto, montamos um modelo de Aprendizado de Máquina (Totalmente executável e Reproduzível).

### 1. Importando as Bibliotecas Necessárias:
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

"""### 2.Selecionando as Características e o Alvo:
Selecionaremos as características e o alvo.
Para este modelo, usaremos as seguintes características:

- mean_temp: Temperatura média anual.
- burnt_area: Área queimada por incêndios florestais.
- total_disasters: Número total de desastres naturais.
- drought_impact: Impacto da seca.

O alvo será:

- avg_temp_anomaly_1961_1990: Anomalia média da temperatura em relação ao período de 1961-1990.
"""

features = ['mean_temp', 'burnt_area', 'total_disasters', 'drought_impact']
target = 'avg_temp_anomaly_1961_1990'

X = merged_data_global[features]
y = merged_data_global[target]

"""### 3. Divisão dos dados em Conjuntos de Treinamento e Teste:"""

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

"""### 4. Treinamento do Modelo:

- Usaremos um modelo de regressão Linear:
"""

model = LinearRegression()
model.fit(X_train, y_train)

"""### 5. Avaliação do Modelo:"""

y_pred = model.predict(X_test)

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Erro Quadrático Médio (MSE): {mse}")
print(f"R-quadrado (R2): {r2}")

"""### 6. Explicação do Modelo e do Resultado:

### Método Aplicado:

Utilizamos o método de Regressão Linear para construir o modelo. Este método tem como objetivo encontrar a melhor reta que representa a relação entre as variáveis independentes (características) e a variável dependente (alvo). No nosso caso, buscamos a reta que melhor descreve a relação entre a anomalia média da temperatura (avg_temp_anomaly_1961_1990) e as características selecionadas (mean_temp, burnt_area, total_disasters, drought_impact).

### Etapas do Método:

- Preparação dos Dados: Selecionamos as características e o alvo do modelo, e dividimos os dados em conjuntos de treinamento e teste.
- Treinamento do Modelo: O modelo de Regressão Linear foi treinado utilizando os dados de treinamento, ajustando os coeficientes da reta para minimizar o erro entre as previsões e os valores reais.
- Avaliação do Modelo: O modelo treinado foi avaliado utilizando os dados de teste. As métricas utilizadas para avaliação foram o Erro Quadrático Médio (MSE) e o R-quadrado (R2).

### Métodos Estatísticos Utilizados:

- Erro Quadrático Médio (MSE): O MSE mede a média dos quadrados das diferenças entre as previsões do modelo e os valores reais. Um valor menor de MSE indica um modelo com melhor desempenho.

- R-quadrado (R2): O R2 mede a proporção da variância na variável dependente que é explicada pelas variáveis independentes. Um valor de R2 mais próximo de 1 indica um modelo com melhor ajuste aos dados.

### Análise dos Resultados:

- Erro Quadrático Médio (MSE): 39.51849814236352
> Este valor representa a média dos quadrados das diferenças entre as previsões do modelo e os valores reais da anomalia de temperatura. Em outras palavras, indica o quão "erradas" são as previsões do modelo, em média. Um valor menor de MSE é desejável, pois indica um modelo com menor erro. No entanto, o valor de MSE por si só não é suficiente para avaliar a qualidade do modelo, pois depende da escala dos dados. Por exemplo, um MSE de 39.5 pode ser considerado bom para um conjunto de dados com valores muito grandes, mas ruim para um conjunto de dados com valores pequenos.

- R-quadrado (R2): -283.45999799315894
> Este valor é preocupante, pois indica que o modelo está tendo um desempenho muito ruim. Um R2 negativo significa que o modelo está se ajustando aos dados pior do que uma linha horizontal, que representa a média dos valores da variável dependente. Em outras palavras, o modelo está fazendo previsões piores do que se simplesmente prevíssemos a média da anomalia de temperatura para todos os casos. Isso sugere que o modelo não está capturando a relação entre as variáveis independentes e a variável dependente, ou que a relação entre elas não é linear.

### Considerações sobre o Modelo Apresentado para a Etapa 3:

O modelo apresentado não é o ideal, sendo utilizado para essa etapa da entrega. O modelo deve ser refinado até a etapa final do projeto.

# **Cronograma**

- Atividade:
__Pesquisa de Trabalhos Correlatos.__<br/>
Descrição:
Revisão da literatura e busca de trabalhos correlatos relacionados ao problema e suas soluções.
Data de conclusão:
26/09

- Atividade:
__Redação do Referencial Teórico.__<br/>
Descrição:
Discussão sobre as alternativas de solução, vantagens e limitações dos trabalhos correlacionados.
Data de conclusão:
28/09

- Atividade:
__Definição dos Conceitos Chave.__<br/>
Descrição:
Definir e apresentar os principais conceitos envolvidos na solução do problema.
Data de conclusão:
29/09

- Atividade:
__Elaboração do Pipeline da Solução.__<br/>
Descrição:
Descrever o pipeline da solução proposta com suas fases e como cada uma será implementada.
Data de conclusão:
29/09

- Atividade:
__Desenvolvimento do Cronograma Detalhado.__<br/>
Descrição:
Elaboração do cronograma com datas das próximas etapas e atividades do projeto.
Data de conclusão:
29/09

- Atividade:
__Revisão Final e Entrega Final.__<br/>
Descrição:
Revisão do conteúdo escrito (Referencial Teórico, Pipeline da Solução, e Cronograma). Submissão das entregas da Etapa 02
Data de conclusão:
30/09

- Atividade:
__Inserção da Base de Dados (.csv).__<br/>
Descrição:
Inserção dos Arquivos .csv dentro do Google Colab
Data de conclusão:
28/10

- Atividade:
__Exploração e análise inicial dos dados.__<br/>
Descrição:
Discussão e análise dos dados empregados
Data de conclusão:
28/10

- Atividade:
__Aplicação do primeiro modelo de aprendizado de máquina.__<br/>
Descrição:
Aplicação do Primeiro Modelo de ML utilizando os dados da Pipeline
Data de conclusão:
28/10

- Atividade:
__Revisão Final e Entrega Final.__<br/>
Descrição:
Revisão do conteúdo. Submissão das entregas da Etapa 03
Data de conclusão:
28/10

# **Referências**

INTERGOVERNMENTAL PANEL ON CLIMATE CHANGE (IPCC). Climate Change 2021: The Physical Science Basis. Contribution of Working Group I to the Sixth Assessment Report [Masson-Delmotte, V., Zhai, P., Pirani, A., Connors, S. L., Péan, C., Berger, S., et al. (Eds.)]. Cambridge University Press, 2021. Disponível em: https://www.ipcc.ch/report/ar6/wg1/. Acesso em: 04 set. 2024.

ORGANIZAÇÃO DAS NAÇÕES UNIDAS. Transformando nosso mundo: a Agenda 2030 para o Desenvolvimento Sustentável. Resolução aprovada pela Assembleia Geral da ONU em 25 de setembro de 2015. Disponível em: https://sdgs.un.org/2030agenda. Acesso em: 04 set. 2024.

PEREIRA, H. M., LEADLEY, P. W., PROENÇA, V., ALKEMADE, R., SCHARLEMANN, J. P. W., FERNANDEZ-MANJARRES, J. F., ... WALPOLE, M. (2010). Scenarios for Global Biodiversity in the 21st Century. Science, 330(6010), 1496-1501. Disponível em: https://doi.org/10.1126/science.1196624 Acesso em: 04 set. 2024.
"""

#@title **Avaliação**
Referencial_teorico = 10 #@param {type:"slider", min:0, max:10, step:1}

Pipeline_solucao = 10 #@param {type:"slider", min:0, max:10, step:1}

Cronograma = 10 #@param {type:"slider", min:0, max:10, step:1}

#@title **Nota Final**
nota = 0.40*Referencial_teorico + 0.40*Pipeline_solucao + 0.20*Cronograma

print(f'Nota final do trabalho {nota :.1f}')

import numpy as np
import pandas as pd

alunos = pd.DataFrame()

lista_nome = []

for i in range(1,6):
  exec("if Aluno" + str(i) + " !='None':  lista = Aluno" + str(i) + ".split(','); lista_nome.append(lista[0]);")

alunos['nome'] = lista_nome
alunos['nota'] = np.round(nota,1)
print()
display(alunos)